### ISSUE TITLE
Initialization erroneously requires trait `Movable`

### ISSUE THREAD

**Issue by camio** [hylo-lang/hylo#1002]
```
public type Bar {
  var y : Int
  public init() {
    &y = 0
  }
}

public type Foo {
  var x : Bar

  public init() {
    &x = .new()
  }
}
```

produces 

```
error: type 'Bar' does not conform to trait 'Movable'
    &x = .new()
    ~~~~~~~~~~~
```

**Comment by kyouko-taiga** [comment]
I don't think this is erroneous. We agreed that assignment syntax would be treated as assignment by the type checker because in general there's no way to tell whether a specific occurrence is assignment or initialization without flow-sensitive analysis. This constraint makes it possible to run type checking without any flow-sensitive information, which is a huge win for the simplicity of the sema.

One way to address your use case is to use a memberwise initializer. Another way would be to escape in unsafe world if we added a free subscript like `uninitialized_pointer<Pointee>(to pointee: set Pointee): PointerToMutable<Pointee>` to stdlib.

I am comfortable keeping the restriction because the issue will only occur when writing immovable types, which should be unusual. The above workarounds can be used to address those rare cases. For the common cases, we have the guarantee that flow sensitive analysis will figure out that the statement is initialization and so it won't generate needless moves.

**Comment by dabrahams** [comment]
I don't think the unsafe solution works because the compiler know that the member has been initialized, and the code should be rejected. If I am comfortable with the member wise approach for now, but we might want to consider explicit member initialization syntax at some point.

**Comment by kyouko-taiga** [comment]
> If I am comfortable with the member wise approach for now, but we might want to consider explicit member initialization syntax at some point.

Sure. Let's keep an eye open to see if the pain becomes too great.

**Comment by camio** [comment]
For the member wise initializer are you suggesting something like the following?

```
public type Bar {
  var y : Int
  public init() {
    &y = 0
  }
}

public type Foo {
  var x : Bar
  private memberwise init

  public init() {
    init( x : .new() )
  }
}
```

**Comment by kyouko-taiga** [comment]
Close:
```
public type Foo {
  var x: Bar
  private memberwise init
  public init() {
    &self = .new(x: Bar())
  }
}
```

**Comment by dabrahams** [comment]
IIUC that there is no other way to initialize members, we should never require private memberwise unit to be explicitly declared.

**Comment by kyouko-taiga** [comment]
We can initialize private members in good old initializers in general:

```hylo
type Circle {
  public var origin: Vector2
  public var radius: Float64

  /// Creates a circle with given `radius` centered at the origin.
  public init(radius: sink Float64) {
    &self.origin = .zero()
    &self.radius = radius
  }
}
```

Memberwise initializers are just like the default initializers we get from Swift. They are roughly sugar for initializers that are easy to synthesize. But they are also more flexible than Swift's because we can change their visibility and have them coexist with other initializers.

I added the explicit declaration requirement because it simplifies shadowing rules in situations where one declares an initializer with the same signature. This situation has legit use cases, like checking for preconditions.

```
type Circle {
  public var origin: Vector2
  public var radius: Float64

  /// Creates a circle with given `radius`, centered at `origin`.
  ///
  /// - Precondition: `radius >= 0.0`
  public init(radius: sink Float64, origin: sink Vector2) {
    precondition(radius >= 0.0)
    &self.origin = origin
    &self.radius = radius
  }
}
```

What made OP's case special is that the type of the field to initialize is immovable, making it impossible to use the assignment syntax. In this situation, a memberwise initializer is the only resort because it allows us to take a shortcut. Since we're generating IR code directly, there is no syntactic ambiguity to resolve. As a result, we can build rvalues in place and don't have to use move operations.

Note that this trick won't work in general because it requires that we're able to inline the memberwise initializer call. That is only possible if the layout of the type to initialize is part of the visible ABI. If it isn't, then we can no longer build rvalues in place. I think we can address this situation by defining an initializer that projects the the storage to initialize in a lambda.

```
// In Module A

// Note: 'Bar' is immovable.
public type Bar {
  public init() {}
}

// Note: 'Foo' is not "frozen"; layout is opaque behind module boundary
public type Foo {
  pubic var x: Bar
  public init<E>(initialize_parts: [E](set Bar) -> Void) {
    initialize_parts(&self.x)
  }
}

// In Module B

import A

let f = Foo(initialize_parts: (_ x) { Bar.init(self. &x) })
```
