### ISSUE TITLE
Expose our custom `fatalError` from `Utils`

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#1066]
Although I personally don't mind `fatalError` reporting `#file` rather `#filePath`, I understand it may be useful for others' setup. However, it is bothering me that `FullPathInFatalErrors.swift` is being copied in every target. I'd rather use a qualified `Utils.fatalError` and have a single definition of these functions in the code base.

**Comment by peter-evans** [comment]
Similar to [this issue](https://github.com/hylo-lang/hylo/issues/643#issuecomment-1888017596), I guess there would be a concern about how to make sure the correct functions get used. This particular case is different from #643 in that no explicit import is needed because the functions are available in the `Swift` library. This would make it a bit more tricky to make sure the correct function is used with a fully qualified name.

What do you think of the following idea. We put the new functions in a struct, which would enforce a fully qualified naming for the static functions we place in there.

Note: I'm not sure what a good name for this struct would be, so I've just called it `Diag` for now.

e.g.
```swift
public struct Diag {
  /// Just like Swift.precondition, but includes the full file path in the diagnostic.
  public static func precondition(
    _ condition: @autoclosure () -> Bool,
    _ message: @autoclosure () -> String = String(),
    file: StaticString = #filePath,
    line: UInt = #line
  ) {
    Swift.precondition(condition(), message(), file: (file), line: line)
  }
}
```
This would be called as `Diag.precondition` after importing `Utils`.

Then we could create a simple CI check in GitHub Actions to grep usages of `precondition` that aren't prefixed with `Diag`, and make sure none have been added outside of the `Diag.swift` file in `Utils`.

```
grep -rP '(?<!Diag\.)precondition' Sources
```

**Comment by dabrahams** [comment]
It should be symlinked

**Comment by kyouko-taiga** [comment]
I actually like @peter-evans's quite a lot. It bothers me that we have these extra `FullPathInFatalErrors.swift` in all targets and the symlinks only feel like a marginal improvement. I don't think we should make it a habit to monkey-patch Swift's standard library even if we don't agree with its choices.

To just spitball, it would also be lovely if this patching could be an opt-in. The experience is actually worse on Xcode because the failure is reported with a deeper call stack. Xcode is actually pretty code at pointing you at the exact source of an error when you call `precondition` or `fatalError` directly.

**Comment by peter-evans** [comment]
> it would also be lovely if this patching could be an opt-in

If this is just to support the setups of some developers, how about this idea.
1. Remove `FullPathInFatalErrors.swift` at the root of modules and, by default, the codebase uses the `Swift.x` functions with `#file`.
2. Add a script under `Tools` that adds `FullPathInFatalErrors.swift` with functions using `#filePath` at the root of modules, and add `FullPathInFatalErrors.swift` to `.gitignore` so that they aren't committed.

Now it can be opt-in. If you want the file path output, then just run the script to setup your local environment.

**Comment by kyouko-taiga** [comment]
> by default, the codebase uses the `Swift.x` functions with `#file`.

You mean by default the code base calls `fatalError`, `preconditionFailure`, etc. without qualification, right? If we write `Swift.fatalError` I believe we'll always get the Swift version of the function, no matter what file is in scope.

> a script under `Tools` that adds `FullPathInFatalErrors.swift`

Or that creates the suggested symlinks.

I would accept such changes.

**Comment by peter-evans** [comment]
> You mean by default the code base calls fatalError, preconditionFailure, etc. without qualification, right?

Yes, that's what I mean. If we remove `FullPathInFatalErrors.swift` at the root of modules, all the existing references just point to the `Swift.` versions of the functions.

> Or that creates the suggested symlinks.

Yes, that could also work. Although I'm not exactly sure how `.gitignore` handles symlinks. Would need to test that.

**Comment by dabrahams** [comment]
> Although I'm not exactly sure how .gitignore handles symlinks. Would need to test that.

Symlinks just work and are already in use.  Why would .gitignore get involved?  We don't want to `git ignore` any of those files.
