### ISSUE TITLE
Support `--version`

### ISSUE THREAD

**Issue by nickpdemarco** [hylo-lang/hylo#1120]
For applications like Compiler Explorer, getting a version identifier (even one produced by a git hash) is useful for triaging issues.

**Comment by peter-evans** [comment]
@kyouko-taiga Do you have a good idea for how to manage the version? I'm more familiar with JVM languages where generally this is achieved by passing the version as a string to the compiler at compile time. It looks like only boolean compiler flags are available in swift.

Here's one possible idea.
1. Create a `Version.swift` file containing just `let version = "unknown"`.
2. Add `Version.swift` to `.gitignore` to prevent changes being committed.
3. Create a script under `Tools/set-version.sh` which re-creates the `Version.swift` file with either a version tag argument, or a git hash.
   e.g.
   ```
    echo "let version = \"$VERSION\"" > Version.swift
    ```

CI could call `set-version.sh` before building, and locally it can be called to set the version to a git hash.

**Comment by kyouko-taiga** [comment]
That's a good idea, I think.

I don't know exactly when one should be supposed to run `set-version.sh`. Any idea how things are done in other compilers? I'll ask what people do for Scala and report back here.

**Comment by peter-evans** [comment]
> I don't know exactly when one should be supposed to run `set-version.sh`

I don't know about other compilers specifically, but in general, for CI:

1. Run `build-and-test.yml` on push to tags, as well as branches.
   ```yml
   on:
     push:
       tags:
         - v*
   ```
2. If the run is triggered by a tag, execute `set-version.sh` and pass the tag string as an arg.
3. If the run is not triggered by a tag, execute `set-version.sh` without an arg, and it uses the `HEAD` git hash.

Then you either tag versions on `main` manually, or create a GitHub release, which also adds a tag.

For local development, I don't know of any easy solution. With this idea, developers would just need to exercise discipline to call `set-version.sh` before compiling, otherwise the version is just `unknown`.

**Comment by kyouko-taiga** [comment]
AFAIC we can go ahead with your idea! Thanks a lot, that's a great proposal.
