### ISSUE TITLE
inconsistent naming in bindings with let vs var

### ISSUE THREAD

**Issue by effinsky** [hylo-lang/hylo#1133]
I don't know in what world except for the world of Swift is `let` the opposite of `var`. They're semantically different idioms for expressing  bindings but the names do not suggest opposing relations with mutability, imo. In any case, I suggest it would be more elegant going the way of Rust with "let" vs "let mut" or the world of Zig with "var" vs "const", or the recent Vlang way of ":=" for immutable binding and "mut xxx :=" for mutable binding. 

I get that this language in now written in Swift but that's no reason to copy things like that from it. 

For your consideration.

**Comment by kyouko-taiga** [comment]
Thanks for your suggestion. We have already spend a lot of time thinking about our binding introducers, and it is becoming unlikely that we'll change at this point. Many pieces of the puzzle have been considered.

In the world of formal semantics, `let` has been fairly well established as a way to define a value for use in another expression. Because most formal description are pure language calculi, it follows that `let` be associated with immutability. `var` also has precedent in formal work, e.g. Odersky et al.'s calculi for call by name and assignment on the top of my head.

Swift is not the only precedent in non-formal languages. Scala uses `var` to introduce mutable bindings and `val` for immutable ones. We made the same choice in early iterations of the design and changed to `let` because it is better established.

`const` is a valid candidate but not necessarily a better choice. It comes with luggage because of the confusing interaction of "constness"  and reference semantics in many languages. AFAIK, Rust's `let mut` is a departure from tradition. The same goes for Vlang.

For future reference, note that it would be best to raise suggestions about the language design in the GitHub discussion rather than opening an issue.

**Comment by dabrahams** [comment]
> changed to let because it is better established

also because it's less visually confusable/mistypable

**Comment by effinsky** [comment]
Sorry about the wrong address for this. 

Just because "const" has been misused in some languages, does not make it any more relevant. something is a "variable", something is a "constant". A proper constant, again see Zig (Zig has made neat choices using "tradition" constructively without being bound by it. Laudable). Ok, so you have a var-iable, and a const-ant. Two things. Let is a different semantic structure -- part of "let identifier equal". It's not a thing akin to a "var-iable". So that duo of var - let definitely does not sit right with me, and  nothing about let suggests it is immutable". 

In a different way, too, Rust is consistent as far as "let" and "let mut". Let ident equal value, and then let mutable ident equal value. Reads as natural as it can.

Um let's not talk Scala. Scala seems like a mess. I'm surprised too, that following careful consideration this is what you've landed on. 

Anyway, to each their own. Will not belabor the point.

**Comment by dabrahams** [comment]
They are not symmetrical concepts. Var implies the creation of storage. But please take any further discussion to the appropriate venue.
