### ISSUE TITLE
Rename  boolean properties of the form `isNounAdjective` => `nounIsAdjective`

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1213]
In context, what you get is `if program.ast.isCoreModuleLoaded {...}`, which grammatically asks whether the AST is “core module loaded,” whatever that means.  

`if program.ast.coreModuleIsLoaded {...}` asks whether the AST has the quality that “the core module is loaded"

**Comment by peter-evans** [comment]
I tried to find some other properties that matched the form `isNounAdjective`. I couldn't find any others besides `coreModuleIsLoaded`, which I raised a PR for here: https://github.com/hylo-lang/hylo/pull/1301

I found [`isAssemblySuitable`](https://github.com/hylo-lang/hylo/blob/main/Sources/IR/Mangling/String%2BAssemblySanitized.swift#L31-L35), which I think is ok because it's saying "{self} is suitable for an assembly," not "is the assembly suitable."

**Comment by dabrahams** [comment]
> I found [`isAssemblySuitable`](https://github.com/hylo-lang/hylo/blob/main/Sources/IR/Mangling/String%2BAssemblySanitized.swift#L31-L35), which I think is ok because it's saying "{self} is suitable for an assembly," not "is the assembly suitable."

That should be `isSuitableForAssembly` or `isSuitableForAnAssembly`.  “x is assembly-suitable” is jargon that only becomes meaningful once you understand what the term “assembly-suitable” means, and our identifiers don't have hyphens to clarify compound adjectives. “x is suitable for assembly” is plain English.

**Comment by dabrahams** [comment]
Since "suitable" isn't defined anywhere I could only assume.

**Comment by dabrahams** [comment]
@peter-evans The regexp `(let|var) +is[A-Z][a-z]+[A-Z]` reveals these that you might have missed:

```
Sources/FrontEnd/TypedProgram.swift
67:    let isTypeCheckingParallel = false
Sources/FrontEnd/TypeChecking/ConstraintSystem.swift
55:  private let isLoggingEnabled: Bool
Sources/FrontEnd/Parse/Parser.swift
 113:    var isPrologueEmpty = attributes.isEmpty
```
