### ISSUE TITLE
Cannot pass a pointer to a member to an external function

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1242]
The following code:
```swift
@ffi("external_function")
private fun external_function(_ p: CVoidPointer)

public type Foo {
  let x: Int
  init() {}

  fun call_external() {
    let p = pointer[to: self]
    external_function(CVoidPointer(base: p.base))
  }
}
```

fails to compile, with error:
```
Examples/test_bug.hylo:10.42-48: error: illegal mutable access
    external_function(CVoidPointer(base: p.base))
                                         ~~~~~~
```

**Comment by lucteo** [comment]
This can be fixed by adding the following in the standard library:
```
/// The address of `x`.
public subscript c_void_pointer<T>(to x: T): CVoidPointer {
  let { yield CVoidPointer(base: Builtin.address(of: x)) }
}
```
and using `c_void_pointer` instead of `pointer[]` + `CVoidPointer` initializer

**Comment by kyouko-taiga** [comment]
I think this is the wrong approach.

We shouldn't abuse the fact that it is currently possible to extract a function pointer from the representation of a lambda to pass functions across FFIs. Instead, we should have a way to write a lambda type in a FFI so that the compiler can:

1. Check that calls to that FFI are well-typed.
2. Safely implement the extraction of a function pointer from the internal representation of lambda values.

We can use `@external` functions as a temporary workaround but we should make no promise about the exact memory layout of a lambda. In fact, I think we should even provide a "Hylo runtime interop library" for people who'd like to interact with Hylo data types from C.
