### ISSUE TITLE
Support the generation of new synthetic functions during monomorphization

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1246]
The following code:
```swift
type FunHolder: Deinitializable {
  var f: []() -> Int

  public init(_ f: sink []()->Int) {
    initialize(&self.f, to: f)
  }
}

public fun main() {
  var fh = FunHolder(fun() -> Int { 13 })
}
```
fails compilation with linker error:
```
ld: Undefined symbols:
  _xF1M8test_bugU8test_bugA9FunHoldersF04init0lTR724selfpT2aTK2Z0pT8lTR70aTR2ZR7YS_7lTtT14selfrT2K714fromK8R7, referenced from:
      l_mFR0UgPointerToMutableF0ainitialize1lTR720pT2gTK1G1T2topT8K3R71lTR70aTR2Z in test_bug.o
      l_mFR0UgPointerToMutableF0ainitialize1lTR720pT2gTK1G1T2topT8K3R71lTR70aTR2Z in test_bug.o
```

**Comment by kyouko-taiga** [comment]
It seems like the emitter doesn't generate move-initializers for lambda types. You can work around the issue by using a memberwise initializer:

```
type FunHolder: Deinitializable {
  public var f: []() -> Int
  public memberwise init
}

public fun main() {
  var fh = FunHolder(f: fun() { 13 })
}
```

**Comment by kyouko-taiga** [comment]
The issue revealed a deeper problem. The call to `initialize(_:to:)` gets monomorphized at the end of IR generation. At the point the emitter thinks that we can safely create witness tables for the types passed as generic arguments and so it will rewrite `initialize(_:to:)` assuming it can call the implementation of `[]() let -> Int`'s move initializer. Unfortunately, this implementation never gets synthesized because IR generation never got to "see" a concrete call.

To fix the issue, we must be able to demand new synthetic functions during monomorphization.
