### ISSUE TITLE
Crash when mutating from a stored lambda.

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1292]
Please see the following code:
```swift
type FunctionStorage<E>: Deinitializable {

  let f: [E]() inout -> Int

  memberwise init

  fun do_call() inout {
    let _ = &self.f()
  }

}
fun store_function<E>(_ f: sink [E]() inout->Int) -> FunctionStorage<E> {
  return .new(f: f)
}


public fun main() {
  var local_variable = 0
  var storage = store_function(fun() -> Int {
    &local_variable = 19 // Crash here
    print("Should reach this point.")
    return 0
  })
  print("before call")
  &storage.do_call()
  print("Done.")
}
```

When running this code, we het a `Segmentation fault: 11` crash when mutating `local_variable` inside the lambda. Removing the mutation will make the code work ok.

Also, if we don't store the lambda in a structure, it all works fine; i.e., the code below works ok:
```swift
public fun main() {
  var local_variable = 0
  var f = fun() -> Int {
    &local_variable = 19 // Now, works fine
    print("Should reach this point.")
    return 0
  }
  print("before call")
  &f()
  print("Done.")
}
```

**Comment by kyouko-taiga** [comment]
This code used to compile but was incorrect. The problem is that one cannot store a lambda whose environment isn't owned. Now the compiler will properly reject the declarations of `FunctionStorage` and `store_function`.

I understand you need a way to get a lambda with access captures as a member of some data structures. I think the only way to do that is to form a lambda in the memberwise initializer of that data structure.

**Comment by kyouko-taiga** [comment]
Note that you _can_ (now that I've fixed more bugs 😅) store a lambda with owned captures.

```
type FunctionStorage<E: Movable & Deinitializable>: Deinitializable { ... }

public fun main() {
  var storage = store_function(fun[var local = 0]() -> Int {
    &local = 19 // All is well here
    print("Should reach this point.")
    return 0
  })

  print("before call")
  &storage.do_call()
  print("Done.")
}
```
