### ISSUE TITLE
Names introduced as generic parameters should be public (or should not implicitly become members)

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#1400]
at 3a3f5a078 typecheck:
```
type X<T>: Deinitializable {
  public typealias Y = Array<T>.Element
}
```

result:

```
slice2.hylo:2.33-40: error: 'Element' is inaccessible due to its protection level
  public typealias Y = Array<T>.Element
                                ~~~~~~~
/Users/dave/src/hylo/StandardLibrary/Sources/Array.hylo:2.19-39: note: 'Element' declared here
public type Array<Element: SemiRegular>: SemiRegular {
                  ~~~~~~~~~~~~~~~~~~~~
slice2.hylo:2.33-40: error: type 'Array<T>' has no member 'Element'
  public typealias Y = Array<T>.Element
                                ~~~~~~~
```

**Comment by kyouko-taiga** [comment]
I don't think generic parameter should become public. Note that they aren't in Swift. In general there is no good reason to write `S<T>.U` (assuming `type S<U> { ... }`) because using `T` directly is clearer.

`Array<T>.Element` is no exception _unless_ the intent is actually to write `Array<T>::Collection.Element`, that is, select the implementation of `Collection.Element` in `Array<T>`. We can't guess the user's intent so we should accept `Array<T>.Element` but not because generic parameters are public.

**Comment by kyouko-taiga** [comment]
Somehow I missed the "or should not implicitly become members" that was part of the issue's title (it wasn't be enough, you see...) One can completely ignore my previous post as its conclusions essentially agree with this perspective.
