### ISSUE TITLE
Cannot get the value of an `Optional` object stored in a type

### ISSUE THREAD

**Issue by lucteo** [hylo-lang/hylo#1403]
The following code fails to compile; the errors are annotated in the code below:
```swift
type OptionalTest {

  var x: Optional<Int>

  public init() {
    &self.x = 13 as _
  }

  public fun extract() -> Int {
  //     ~~~                   error: parameter was consumed
    if let r: Int = self.x {
    // ~~~~~~~~~~              note: escape happens here
      return r.copy()
    } else {
      fatal_error()
    }
  }

}
```

**Comment by lucteo** [comment]
Additional notes:
* can't copy an `Optional` object; thus I can't extract the value from a copy
* even if I re-initialize the optional after the `if` statement; the compiler still complains

**Comment by kyouko-taiga** [comment]
Narrowing conversions are consuming. There's an [open issue](https://github.com/hylo-lang/hylo/issues/1099) for implementing a non-consuming variant.

> can't copy an Optional object; thus I can't extract the value from a copy

You could write an extension of `Optional` to add conformance to `Copyable` when the wrapped value is copyable. It's possible you'll hit a bug, though, because I didn't have time to put enough efforts on union types yet.

> even if I re-initialize the optional after the if statement; the compiler still complains

It's no good if you re-initialize the optional after the test since you will have returned from the first branch. So the compiler is correct. Here's what you should write instead:

```
public fun extract() -> Int {
    if let r: Int = self.x {
      let x = r.copy()
      &self.x = .none() // Re-initialization occurs before we return.
      return x
    } else {
      fatal_error()
    }
  }
```

See also this [post in GH discussions](https://github.com/orgs/hylo-lang/discussions/1165).
