### ISSUE TITLE
Large buffer literals lead to slow inference

### ISSUE THREAD

**Issue by tothambrus11** [hylo-lang/hylo#1533]
Int8 is defined to be expressible by string literal by a conformance to ExpressibleByIntegerLiteral. 

That makes the following compile:
```hylo
let a: Int8 = 0
_ = a
```

However, when having Int8 the element type of a buffer, I can no longer use the integer literal:
```hylo
let buffer: Int8[5] = [0,0,0,0,0]
_ = buffer

// error: cannot initialize object of type 'Int8[5]' with value of type 'Int8[5]'
//    let buffer: Int8[5] = [0,0,0,0,0]
```

And if I accidentally wrote 100 elements in the initializer (In the theoretical case when I don't know how to initialize a buffer in any other way), the compiler seemingly never terminates:

```hylo
let buffer: Int8[100] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
_ = buffer
```

**Comment by kyouko-taiga** [comment]
The problem has nothing to do with `ExpressibleByLiteral`. Buffers are simply not implemented and so nothing the compiler says about a buffer should be used as a premise to deduce any fact about the type systems or its bugs.

The seemingly non-termination thing is because the constraint system becomes too large and backtracks too many times, as `Int8` is not the default type for inferring integer literal. Swift has had this issue and I think the fix was to commit more early to a choice. At the very least I guess this is something we can do.
