### ISSUE TITLE
Encapsulate the internal mutation of the type checker

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#659]
Most methods of the type checker are mutating because nearly all operations are lazy, to deal with forward and recursive references. Unfortunately, that makes the type checker harder to use and reason about.

If we look more closely at the checker's implementation, we distinguish two kinds of methods.
- The `checkXXX` methods take an AST node and verify if it is well typed. Those are eventually called on every node as the AST is walked.
- Other methods compute some properties about a node or a type.

All of these methods may update the property maps of the type checker (i.e., the type annotations that are attached to a program once type checking/inference is done) as well as some internal memoization caches. That's why they are all mutating.

It is not immediately obvious why a method like `conformedTraits(of:in:)` has to be mutable. It's only after we look at its body and notice that it is initiating type checking of some declarations to compute its result, thus causing internal mutation. Further, the caller does not care whether or not the checker updated its state; it only wants a set of traits. So the fact that computing such a set causes mutation is arguably an implementation detail. That is in contrast with a method like `check(module:)` which promises to update property maps.

Another important observation is that property maps are modified monotonically. For example, `declTypes` is only changed by extending it with new key-value pairs. So I think it's actually possible to reason about "concurrent" mutation of these property maps, which is encouraging because it means there's likely a sane and principled way to parallelize the type checker.

It also means that property maps could be implemented as shared mutable objects (e.g., with Dave's `Utils.SharedMutable`) so that the checker's methods no longer have to be mutating. The only property that has to be upheld is that all nodes must be eventually checked, thus ensuring that the property maps are "complete".

**Comment by dabrahams** [comment]
Using `SharedMutable` instead of treating these property maps as parts and just using mutation directly would probably create a large efficiency hit, as closures need to be created, passed to dispatch, and potentially queued, for every access.  The uniqueness checks currently in play are comparatively very cheap.  `SharedMutable` is only reasonable for files because we don't create new files from their names all that often. 
Also, the property maps are associated with a particular set of modules, so it's not like they can be shared globally; that implies an additional layer of lookup.

We don't yet have a great way to model fine-grained access to shared resources in a value-semantic universe, and I wouldn't be too sanguine about our ability to hide the mutation that's actually there, at least not without some new ideas.  Remember that encoding mutation in the type system is part of the glue holding the soundness of the system together.  

Incidentally, this is the sort of thing Swift actors are supposed to encode, but then you have to buy into the whole async/await package.

**Comment by dabrahams** [comment]
I think there's a way to make shared monotonic mutation fit the model, but I do think the model needs to be extended to do that. I wonder how many of the well-understood cases of shared mutation are (or can be viewed as) monotonic. Also note those closures are non-escaping so costs might not be as bad as I presume. We should measure of course!

**Comment by kyouko-taiga** [comment]
Implemented by #845.
