### ISSUE TITLE
Configure linkage of synthesized declarations

### ISSUE THREAD

**Issue by kyouko-taiga** [hylo-lang/hylo#848]
IR functions have a `linkage` property that is eventually used to determine the visibility of the symbol in object files. Declarations exported outside of their module (e.g., public functions at module scope) have "external" linkage; others have "module" linkage.

Currently, linkage for lowered synthesized functions is always "external", even for declarations that were generated for a non-public conformance. As a result, they will always show up with external linkage in object files, hampering possible code size reductions.

To fix this issue, `SynthesizedFunctionDecl` should get a `linkage` property that is configured depending on the visibility of the conformance for which an instance is created. Then, LLVM code generation can read this property to determine the appropriate linkage.

**Comment by peter-evans** [comment]
The code comment here points to a different issue which looks unrelated to me. Fairly sure it's about this issue. Mentioning here to double check.

https://github.com/hylo-lang/hylo/blob/ed677cb4dfa41d7a4b5fb4421207b51c92369c53/Sources/CodeGen/LLVM/Transpilation.swift#L497-L503

**Comment by peter-evans** [comment]
I've [made changes](https://github.com/hylo-lang/hylo/compare/main...peter-evans:hylo:linkage) to configure the linkage of synthesized declarations. It seems to work for the majority of cases, but for some reason the `.hylo` test files that make use of function [`reserve_capacity`](https://github.com/hylo-lang/hylo/blob/4bd143e1ab22071495070fba89893d98f44edb0b/StandardLibrary/Sources/Array.hylo#L53) in `Array` (just 5 of them) are failing with the error below... and _only_ those test cases. If I remove the 5 test files using that function, everything else passes. I can't understand what is special about the `reserve_capacity` function. I'm wondering if it might be an unrelated issue that I'm seeing that has only surfaced because of the linkage change. 🤔 

```
Building for production...
[10/10] Linking hc
Build complete! (51.50s)
[534/534] Testing LibraryTests.LibraryTests/test_compileAndRun_StrideableTests
Test Suite 'Selected tests' started at 2024-02-07 16:00:16.327Test Suite 'EndToEndTests' started at 2024-02-07 16:00:16.329Test Case 'EndToEndTests.test_compileAndRun_Break' started at 2024-02-07 16:00:16.329/workspaces/hylo/Tests/EndToEndTests/TestCases/Break.hylo:1: error: EndToEndTests.test_compileAndRun_Break : success was expected, but processing failed with thrown error: Process.NonzeroExit (status: 1)
Command line: "/usr/bin/clang++" "-o" "/tmp/E1F3DC7A-66E0-4E93-8F19-2EADB528FAFF" "/tmp/4422A05F-2E6F-4569-8ACB-46D55F4BA1F1/Hylo.o" "/tmp/4422A05F-2E6F-4569-8ACB-46D55F4BA1F1/Break.o"

  standard output:
  -------------

  -------------

  standard error:
  -------------
/usr/bin/ld: /tmp/4422A05F-2E6F-4569-8ACB-46D55F4BA1F1/Break.o: in function `mFR0UgPointerToMutableAgPointerToMutableH6unsafe0sT5tT14selfrTgbTaTK1Z1gTK1G7Pointee0K5iH41tT28capacityaTR2Zepayload_headerKb.resume.0':
Break:(.text+0x106a): undefined reference to `xF0R0U5ArrayA5ArrayF0greserve_capacity0lTtT14selfrT4bTaTK1Z1gTK1G7Element10pT1aTR2ZR7YQ7ilTtT14selflTtT11crT1K910pT2K9R70R7'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```
