### ISSUE TITLE
Explicit generic arguments aren't enough either

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#921]
Same message as, but apparently different bug from #819 

```
type X<T>: Movable, Deinitializable {

  memberwise init

}

fun f<T>()-> X<T> {
  let x = X<T>() // error: not enough contextual information to infer generic arguments
  return x
}
```

**Comment by kyouko-taiga** [comment]
Problem seems to be that `T` doesn't get skolemized when it appears as an explicit generic argument in an arbitrary expression. The problem does not occur if we explicitly type the binding:

```
fun f<T>() -> X<T> {
  var x: X<T> = X()
  return x
}
```

**Comment by kyouko-taiga** [comment]
The problem is trickier to solve than I hoped.

Basically the issue is that the current algorithm used to decide whether or not it should open a generic type parameter in the environment defining that parameter is broken. Specifically, when the compiler sees `X<T>()`, it mistakenly interprets `T` as a universally quantified parameter because it appears in a call.

The parameter is opened because of these lines in the type checker: https://github.com/hylo-lang/hylo/blob/3166db52f95b333152461f1f19fbf3a77b8d7230/Sources/FrontEnd/TypeChecking/TypeChecker.swift#L3294-L3297

The comment is wrong. References to constructors may be skolemized when the constructor the scope of use isn't within the constructor itself.

I'm not sure we can solve this issue without bringing back `SkolemType` and use it to get a finer control over skolemization.
