### ISSUE TITLE
Builtins are implicitly copied in Hylo code

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#944]
I understand that implicit copying happens at the IR level but I find it quite counterintuitive to program with such different language rules for builtins in Hylo.

```
type X {
  memberwise init
  var a: Builtin.ptr

  init(other: X) {
    &a = other.a // shouldn't compile without a copy() IMO.
  }
}
```

**Comment by kyouko-taiga** [comment]
It is difficult to implement support for methods operating on built-in types because of various technical reasons. Since built-in types are not supposed to be used outside of the standard library we thought the implicit copy would be an acceptable simplification (it was actually your suggestion ;)). Note that built-in types are also implicitly zero-initialized and implicitly deinitialized.

The easiest way to get more explicit would be to define built-in copy functions rather than methods.

**Comment by dabrahams** [comment]
> it was actually your suggestion 

I *thought* I meant they should be implicitly copied only in IR, but I may have forgotten.

> The easiest way to get more explicit would be to define built-in copy functions rather than methods.

Ah yes, I see the problem.  I'm not sure I want to ask for any change now… It almost makes me want to use:

```
/// An explicitly-copyable wrapper for a `Builtin` type `T`.
type ExplicitCopy<T>: Regular {
  memberwise init
  var raw: T
}
```

😉
