### ISSUE TITLE
Precondition failure @ 3166db52

### ISSUE THREAD

**Issue by dabrahams** [hylo-lang/hylo#969]
Apply this patch to 3166db52 for a precondition failure in `swift test --filter testBinary`:

```diff
diff --git a/Library/Hylo/DynamicBuffer.hylo b/Library/Hylo/DynamicBuffer.hylo
index aec6fa54..4c476c6f 100644
--- a/Library/Hylo/DynamicBuffer.hylo
+++ b/Library/Hylo/DynamicBuffer.hylo
@@ -24,7 +24,7 @@ public type DynamicBuffer<Header: Deinitializable, Element>: Deinitializable {
   /// A null value denotes an empty buffer. Otherwise, `storage` points at an instance of
   /// `BufferHeader` that is followed by a region capable of storing at most `self.capacity`
   /// instances of `Element`, offset to satisfy `Element`'s alignment requirement'.
-  var storage: PointerToMutable<Never>
+  var storage: MemoryAddress
 
   /// Creates an empty instance.
   public init() {
```
/Users/dave/src/hylo/Sources/Core/Types/AnyType.swift:134: Precondition failed

**Comment by dabrahams** [comment]
A variety of related asserts occur if you replace other uses of `PointerToMutable<Never>` with `MemoryAddress`, including:

/Users/dave/src/hylo/Sources/CodeGen/LLVM/TypeLowering.swift:32: Fatal error: 'MemoryAddress' is not representable in LLVM

**Comment by peter-evans** [comment]
I can see there is a typealias in the standard library. `typealias MemoryAddress = PointerToMutable<Never>`

The only use of `PointerToMutable<Never>` I can find in the tests is [this one](https://github.com/hylo-lang/hylo/blob/ed677cb4dfa41d7a4b5fb4421207b51c92369c53/Tests/LibraryTests/TestCases/PointerToMutableTests.hylo#L4).

I tried replacing it with `MemoryAddress` and the program seems to compile and run without error.

I think this is fixed in the [latest version](https://github.com/hylo-lang/hylo/commit/ed677cb4dfa41d7a4b5fb4421207b51c92369c53) of the compiler.

**Comment by kyouko-taiga** [comment]
This issue is obsolete. Thanks for having checked @peter-evans
